# Generated by Django 4.1.7 on 2023-02-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Объявление")),
                ("author", models.CharField(max_length=50, verbose_name="Автор")),
                ("price", models.PositiveBigIntegerField(verbose_name="Цена")),
                (
                    "description",
                    models.TextField(
                        max_length=1000, null=True, verbose_name="Описание"
                    ),
                ),
                ("address", models.CharField(max_length=500, verbose_name="Адрес")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Статус объявления"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Категория")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["id"],
            },
        ),
    ]
