# Generated by Django 4.1.7 on 2023-03-06 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=10,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator],
            ),
        ),
    ]
