# Generated by Django 4.1.7 on 2023-02-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location",
            new_name="location_id",
        ),
    ]
