# Generated by Django 4.1.7 on 2023-03-06 11:50

import ads.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                null=True,
                validators=[ads.models.birth_date_validator],
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="ads",
            name="is_published",
            field=models.BooleanField(
                default=False,
                validators=[ads.models.validate_is_published],
                verbose_name="Статус объявления",
            ),
        ),
        migrations.AlterField(
            model_name="ads",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Объявление",
            ),
        ),
        migrations.AlterField(
            model_name="ads",
            name="price",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=10,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Почта"),
        ),
    ]
