# Generated by Django 4.1.7 on 2023-03-06 12:48

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_user_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[ads.models.validate_email],
                verbose_name="Почта",
            ),
        ),
    ]
