# Generated by Django 4.1.7 on 2023-03-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat",
                to="ads.category",
                verbose_name="Категория",
            ),
        ),
    ]
